FROM python:3.12

# Application port
EXPOSE 5000

# Set workdir and copy application
WORKDIR /app
COPY ./app/back .

# Install libraries
RUN pip install -r requirements.txt

# Setup startup command
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]